<p class="font-weight-bold"  style="font-size:12px">  <img src="{{ asset('img/site/new/title/file.svg') }}" style="width: 20px;height: 20px;position: relative;top: 0px;" /> &nbsp;پروژه‌ها</p>
  <hr>
  <P style="font-size: 12px;" id="projectTitlex0"></P>
  <P style="font-size: 12px;"><span style="font-size: 12px;"><span style="font-size:11px" id="textStartP0"></span>  <span style="font-size:11px;color:blue;"  id="projectMEx0" ></span> <span style="font-size:11px;color:blue;" id="projectYEx0"></span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-size:11px;" id="textEndP0"></span>  <span style="font-size:11px;color:blue;" id="projectMEEx0"></span> <span style="font-size:11px;color:blue;" id="projectYEEx0"></span></span></P>
  <P style="font-size: 12px;"><span style="font-size:11px" id="EmployerText0"></span><span style="font-size:11px" id="ProjectEmployerx0"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-size:11px" ><a href="#" target="_black" style="font-size:11px;color:blue;" id="ProjectLink0" ></a></span></P>
  <P style="font-size: 12px;" id="projectTitlex1"></P>
  <P style="font-size: 12px;"><span style="font-size: 12px;"><span style="font-size:11px" id="textStartP1"></span>  <span style="font-size:11px;color:blue;" id="projectMEx1" ></span> <span style="font-size:11px;color:blue;" id="projectYEx1"></span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-size:11px;" id="textEndP1"></span>  <span style="font-size:11px;color:blue;" id="projectMEEx1"></span> <span style="font-size:11px;color:blue;" id="projectYEEx1"></span></span></P>
  <P style="font-size: 12px;"><span style="font-size:11px" id="EmployerText1"></span><span style="font-size:11px" id="ProjectEmployerx1"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-size:11px" ><a href="#" target="_black" style="font-size:11px;color:blue;" id="ProjectLink1" ></a></span></P>
  <P style="font-size: 12px;" id="projectTitlex2"></P>
  <P style="font-size: 12px;"><span style="font-size: 12px;"><span style="font-size:11px" id="textStartP2"></span>  <span style="font-size:11px;color:blue;" id="projectMEx2" ></span> <span style="font-size:11px;color:blue;" id="projectYEx2"></span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-size:11px;" id="textEndP2"></span>  <span style="font-size:11px;color:blue;" id="projectMEEx2"></span> <span style="font-size:11px;color:blue;" id="projectYEEx2"></span></span></P>
  <P style="font-size: 12px;"><span style="font-size:11px" id="EmployerText2"></span><span style="font-size:11px" id="ProjectEmployerx2"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-size:11px" ><a href="#" target="_black" style="font-size:11px;color:blue;" id="ProjectLink2" ></a></span></P>
  <P style="font-size: 12px;" id="projectTitlex3"></P>
  <P style="font-size: 12px;"><span style="font-size: 12px;"><span style="font-size:11px" id="textStartP3"></span>  <span style="font-size:11px;color:blue;" id="projectMEx3" ></span> <span style="font-size:11px;color:blue;" id="projectYEx3"></span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-size:11px;" id="textEndP3"></span>  <span style="font-size:11px;color:blue;" id="projectMEEx3"></span> <span style="font-size:11px;color:blue;" id="projectYEEx3"></span></span></P>
  <P style="font-size: 12px;"><span style="font-size:11px" id="EmployerText3"></span><span style="font-size:11px" id="ProjectEmployerx3"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-size:11px" ><a href="#" target="_black" style="font-size:11px;color:blue;" id="ProjectLink3" ></a></span></P>